spring.application.name=smart-settlement
# Database Setting (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/settlement
spring.datasource.username=postgres
spring.datasource.password=comt202603
spring.jpa.hibernate.ddl-auto=update

# Redis Setting
spring.data.redis.host=localhost
spring.data.redis.port=6373